name: deploy-api
on:
  push:
    branches: [main]
    paths:
      - "cmd/api/**"
      - "api/**"
      - ".github/**"
      - "config/**"
      - "**.go"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Tailscale
        uses: tailscale/github-action@ce41a99162202a647a4b24c30c558a567b926709
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          args: --ssh
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Install mrsk
        run: gem install mrsk
      - name: Connect to deploy box
        run: ssh-keyscan -H lanyard-prod >> ~/.ssh/known_hosts
      - run: ./cmd/api/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
