name: deploy-api
on:
  push:
    branches: [main]
    paths:
      - "cmd/api/**"
      - "api/**"
      - ".github/**"
      - "**.go"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.2.1"
      - name: Install mrsk
        run: gem install mrsk
      - run: ./cmd/api/deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
