name: deploy-api
on:
  push:
    branches: [main]
    paths:
      - "cmd/api/**"
      - "api/**"
      - ".github/**"
      - "**.go"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - run: ./cmd/api/deploy.sh
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
